

services:
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: khaled552002
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: